### PR TITLE
Add "module" entry point for ESM consumers

### PR DESCRIPTION
**Pull request by TehShrike**
This allows bundlers to tree-shake and only pull in the specific functions that people want to import.

### CODE REVIEW

**Comment by TehShrike** [comment]
Some more context: https://github.com/rollup/rollup/wiki/pkg.module

**Comment by TehShrike** [comment]
Oh hey, the ESM code isn't even in the published bundle!

**Comment by TehShrike** [comment]
There we go.

**Comment by alekseykulikov** [comment]
thanks, published as 3.2.1

**Pull request merged**
